language: nix
script: |
  bash -c '
    set -e
    set -x

    nixpkgs_rev=bea585cf420f7744441d6c7297fafb9401bd3c6d

    curl -L https://github.com/NixOS/nixpkgs/archive/${nixpkgs_rev}.tar.gz | tar -xz -C $HOME

    export NIX_PATH=nixpkgs=$HOME/nixpkgs-${nixpkgs_rev}
    export SENTRY=""
    export WS_ENDPOINT=""
    export HTTP_ENDPOINT=""

    mkdir -p ~/projects/src/github.com/corpix
    ln -s ~/projects/src/github.com/corpix/go-boilerplate $(pwd)

    nix-shell --command "make test"
  '

cache:
  directories:
    - /nix
    - ~/projects
